// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func printToConsole(content string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_printToConsole_5a85`,
		Function: `function __templ_printToConsole_5a85(content){console.log(content)
}`,
		Call:       templ.SafeScript(`__templ_printToConsole_5a85`, content),
		CallInline: templ.SafeScriptInline(`__templ_printToConsole_5a85`, content),
	}
}

var _ = templruntime.GeneratedTemplate
